#!/usr/bin/env bash

rm -f /usr/local/bin/miniscript-run >/dev/null
[[ -z "$(command -v miniscript-run)" ]] && \
        install $0 /usr/local/bin/ 2>/dev/null || true

function help(){

    echo "miniscript-run '<miniscript>'";
    echo "miniscript-run 'pk_h(test)'";exit

}
if [[ "$1" == "help" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help; exit
fi

function install(){

    [ ! -d miniscript ] && \
        $(which git) clone --depth 1 https://github.com/sipa/miniscript.git

    rm -rf /usr/local/bin/miniscript >/dev/null
    [ -d miniscript ] && \
    cd miniscript/ && \
        rm miniscript && \
        make && \
        ls && \
        install ./miniscript /usr/local/bin/ || true && \
        cd .. || file $(which miniscript);

    rm -f /usr/local/bin/miniscript-run >/dev/null
    [[ -z "$(command -v miniscript-run)" ]] && \
        install $0 /usr/local/bin/ >/dev/null
exit
}
if [[ "$1" == "install" ]]; then
    install;
fi
#
for var in "$@"
do
    echo "$var" | $(which miniscript) 2>/dev/null;exit || \
    echo "$var" | ./miniscript/miniscript;exit || help
done
help
